// Generates src/components/ui/icons.generated.ts from the icon packages (dev dependencies only;
// nothing ships at runtime but the paths we use).
//   - UI icons: Lucide (ISC) — https://lucide.dev — mapped from Docket's semantic names below.
//   - Platform marks: Simple Icons (CC0-1.0) — https://simpleicons.org — keyed by provider key.
// Usage: pnpm icons   (then commit the generated file). Add an icon by adding a line to ICONS.
import fs from "node:fs";

/** Docket name → Lucide icon name. Keep names about meaning ("failures"), not shape ("triangle"). */
const ICONS = {
  calendar: "calendar",
  posts: "list",
  compose: "square-pen",
  generate: "sparkles",
  jobs: "layers",
  review: "square-check-big",
  failures: "triangle-alert",
  media: "image",
  accounts: "users",
  voice: "mic",
  settings: "settings",
  search: "search",
  chevronDown: "chevron-down",
  chevronRight: "chevron-right",
  inbox: "inbox",
  logOut: "log-out",
  plus: "plus",
  check: "check",
  close: "x",
  arrowLeft: "arrow-left",
  arrowRight: "arrow-right",
  arrowUp: "arrow-up",
  externalLink: "external-link",
  clock: "clock",
  trash: "trash",
  upload: "upload",
  refresh: "refresh-cw",
  link: "link",
  copy: "copy",
  key: "key-round",
  webhook: "webhook",
  userPlus: "user-plus",
  flask: "flask-conical",
  info: "info",
  circleCheck: "circle-check",
  circleAlert: "circle-alert",
  activity: "activity",
  bell: "bell",
  slidersHorizontal: "sliders-horizontal",
  overview: "layout-dashboard",
  circle: "circle",
};

/** Provider key → Simple Icons slug. The mock provider has no brand; it uses the "flask" UI icon. */
const PROVIDERS = {
  facebook: "facebook",
  instagram: "instagram",
  threads: "threads",
  bluesky: "bluesky",
  x: "x",
};

// Package "exports" hide package.json from require.resolve, so read the installed directories.
const pkgDir = (name) => new URL(`../node_modules/${name}/`, import.meta.url).pathname;
const version = (name) => JSON.parse(fs.readFileSync(`${pkgDir(name)}package.json`, "utf8")).version;
const lucideDir = pkgDir("lucide-static");
const lucideVersion = version("lucide-static");
const nodes = JSON.parse(fs.readFileSync(`${lucideDir}icon-nodes.json`, "utf8"));
const siDir = pkgDir("simple-icons");
const siVersion = version("simple-icons");
const siData = JSON.parse(fs.readFileSync(`${siDir}data/simple-icons.json`, "utf8"));
const siList = Array.isArray(siData) ? siData : siData.icons;

const ui = {};
for (const [name, lucide] of Object.entries(ICONS)) {
  const node = nodes[lucide];
  if (!node) throw new Error(`Lucide has no icon "${lucide}" (for "${name}")`);
  ui[name] = node.map(([tag, attrs]) => [tag, Object.fromEntries(Object.entries(attrs).filter(([k]) => k !== "key"))]);
}

const marks = {};
for (const [key, slug] of Object.entries(PROVIDERS)) {
  const svg = fs.readFileSync(`${siDir}icons/${slug}.svg`, "utf8");
  const d = /<path d="([^"]+)"/.exec(svg)?.[1];
  const title = /<title>([^<]+)<\/title>/.exec(svg)?.[1];
  const entry = siList.find((i) => i.title === title || i.slug === slug);
  if (!d || !title || !entry) throw new Error(`Simple Icons: cannot read "${slug}"`);
  marks[key] = { title, hex: `#${entry.hex}`, path: d };
}

/** One entry per line, so a diff shows exactly which icon changed. */
const lines = (obj) => Object.entries(obj).map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`).join("\n");

const out = `// Generated by scripts/generate-icons.mjs — do not edit by hand; run \`pnpm icons\`.
// UI icons: Lucide v${lucideVersion} (ISC, https://lucide.dev). Platform marks: Simple Icons v${siVersion} (CC0-1.0).

export type IconNode = readonly (readonly [tag: string, attrs: Readonly<Record<string, string>>])[];

export const ICON_NODES = {
${lines(ui)}
} as const satisfies Record<string, IconNode>;

export const PROVIDER_MARKS = {
${lines(marks)}
} as const satisfies Record<string, { title: string; hex: string; path: string }>;
`;
fs.writeFileSync(new URL("../src/components/ui/icons.generated.ts", import.meta.url), out);
console.log(`wrote ${Object.keys(ui).length} icons and ${Object.keys(marks).length} platform marks`);
